import { ReactNode } from 'react';
import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import ClientAuthGuard from '@/components/ClientAuthGuard';
import AppShell from '@/components/AppShell';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Lets the fixed bottom bar sit under the iPhone home indicator via
  // env(safe-area-inset-bottom).
  viewportFit: 'cover',
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AuthGuard>
            <AppShell>{children}</AppShell>
          </AuthGuard>
        </AuthProvider>
      </body>
    </html>
  );
}

async function AuthGuard({ children }: { children: ReactNode }) {
  const session = await getServerSession(authOptions);

  // Get the current pathname (you'll need to pass this from a client component)
  // For now, we'll handle this in the client component below
  return <ClientAuthGuard>{children}</ClientAuthGuard>;
}
