import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import ClientAuthGuard from '@/components/ClientAuthGuard';
import Navigation from '@/components/Navigation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AuthGuard>
            <Navigation />
            <main className="min-h-screen bg-background">{children}</main>
          </AuthGuard>
        </AuthProvider>
        <footer className="border-t bg-muted/50 px-6 py-4">
          <div className="max-w-7xl mx-auto flex justify-between">
            <span className="text-sm text-foreground">© Copyright 2025.</span>
            <div>
              <p className="text-sm text-foreground">
                Questions? Email&nbsp;
                <a href="mailto:jmasongson@bchousing.org" className="underline">
                  support.
                </a>
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}

async function AuthGuard({ children }: { children: ReactNode }) {
  const session = await getServerSession(authOptions);

  // Get the current pathname (you'll need to pass this from a client component)
  // For now, we'll handle this in the client component below
  return <ClientAuthGuard>{children}</ClientAuthGuard>;
}
